### ISSUE TITLE
Can't run zktop on CentOS 6 with python2.6

### ISSUE THREAD

**Issue by xluffy** [phunt/zktop#15]
When I run `zktop` with python2.6, I have an error like that

```
Traceback (most recent call last):
  File "./zktop.py", line 23, in <module>
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'
```

In python2.6, `sys.version_info` don't have `major` attribute. I can fix it by replace `sys.version_info.major` with `sys.version_info[0]`. It works on both python2.6 and python2.7.

But I don't know you would like to support python2.6 or not. Maybe I can send a pull request

**Comment by phunt** [comment]
Hi @xluffy - that check was recently introduced via a pull request from @ArneBachmann see 
https://github.com/phunt/zktop/pull/14

afaik it was working in that environment before, we just didn't notice the regression (I'm on a mac which worked with python 2.7/3, Arne is on a windows box iiuc), thanks for reporting it. If you would be kind enough to provide a pull request with the fix I'll review and include it. Thanks!

**Comment by xluffy** [comment]
Yes, I see. CentOS 6.x still is popular version. Default python on CentOS 6.x still is 2.6. I'll send a pull request. Thanks!

**Comment by phunt** [comment]
Closing this issue as the pull request has been submitted/committed. Thanks @xluffy !
